ALTER TABLE Jogos ADD CorPeca INT NULL;
ALTER TABLE Jogos ADD SequenciaEntradaUsuarioSala INT NULL;
ALTER TABLE Jogos ADD PosLinhaInicial INT NULL;
ALTER TABLE Jogos ADD PosColunaInicial INT NULL;
ALTER TABLE Jogos ADD PosLinhaAtual INT NULL;
ALTER TABLE Jogos ADD PosColunaAtual INT NULL;
ALTER TABLE Jogos ADD DataEntradaSala DATETIME NULL;
ALTER TABLE Jogos ADD DataUltimaResposta DATETIME NULL;
ALTER TABLE Jogos ADD PerguntaAtualFeitaEm DATETIME NULL;
ALTER TABLE Jogos ADD Acertos INT NOT NULL DEFAULT 0;
ALTER TABLE Jogos ADD Erros INT NOT NULL DEFAULT 0;






