ALTER TABLE PERSONAGENS ADD Nivel int;
ALTER TABLE PERSONAGENS ADD Id_tema int;

ALTER TABLE [dbo].[PERSONAGENS]  WITH CHECK ADD  CONSTRAINT [FK_Pers_Tema] FOREIGN KEY([Id_tema])
REFERENCES [dbo].[Temas] ([Id_tema])
GO

ALTER TABLE [dbo].[PERSONAGENS] CHECK CONSTRAINT [FK_Pers_Tema]
GO