DECLARE @Layout VARCHAR(50) = '12 Jogadores, 4 Perguntas mesmo Tema';
DECLARE @IdLayout int;
DECLARE @IdTrilha INT;

SET @IdLayout = (SELECT L.Id FROM LayoutTabuleiro L WHERE L.Descricao = @Layout);
PRINT @IdLayout;

SET @IdTrilha = 4;
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 01, 5, 12);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 02, 5, 11);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 03, 5, 10);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 04, 5, 9);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 05, 5, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 06, 6, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 07, 7, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 08, 8, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 09, 8, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 10, 8, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 11, 8, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 12, 8, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 13, 7, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 14, 6, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 15, 5, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 16, 4, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 17, 4, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 18, 4, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 19, 4, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 20, 4, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 21, 5, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 22, 6, 6);

SET @IdTrilha = 5;
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 01, 6, 12);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 02, 6, 11);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 03, 6, 10);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 04, 6, 9);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 05, 6, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 06, 7, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 07, 8, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 08, 8, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 09, 8, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 10, 8, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 11, 8, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 12, 7, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 13, 6, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 14, 5, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 15, 4, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 16, 4, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 17, 4, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 18, 4, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 19, 4, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 20, 5, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 21, 6, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 22, 6, 6);

SET @IdTrilha = 6;
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 01, 7, 12);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 02, 7, 11);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 03, 7, 10);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 04, 7, 9);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 05, 7, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 06, 8, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 07, 8, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 08, 8, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 09, 8, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 10, 8, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 11, 7, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 12, 6, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 13, 5, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 14, 4, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 15, 4, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 16, 4, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 17, 4, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 18, 4, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 19, 5, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 20, 6, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 21, 7, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 22, 6, 6);
