DECLARE @Layout VARCHAR(50) = '12 Jogadores, 4 Perguntas mesmo Tema';
DECLARE @IdLayout int;
DECLARE @IdTrilha INT;

SET @IdLayout = (SELECT L.Id FROM LayoutTabuleiro L WHERE L.Descricao = @Layout);
PRINT @IdLayout;

SET @IdTrilha = 7;
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 01, 12, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 02, 11, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 03, 10, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 04, 9, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 05, 8, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 06, 8, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 07, 8, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 08, 8, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 09, 7, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 10, 6, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 11, 5, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 12, 4, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 13, 4, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 14, 4, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 15, 4, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 16, 4, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 17, 5, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 18, 6, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 19, 7, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 20, 8, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 21, 8, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 22, 6, 6);

SET @IdTrilha = 8;
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 01, 12, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 02, 11, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 03, 10, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 04, 9, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 05, 8, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 06, 8, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 07, 8, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 08, 7, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 09, 6, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 10, 5, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 11, 4, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 12, 4, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 13, 4, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 14, 4, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 15, 4, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 16, 5, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 17, 6, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 18, 7, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 19, 8, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 20, 8, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 21, 8, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 22, 6, 6);

SET @IdTrilha = 9;
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 01, 12, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 02, 11, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 03, 10, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 04, 9, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 05, 8, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 06, 8, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 07, 7, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 08, 6, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 09, 5, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 10, 4, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 11, 4, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 12, 4, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 13, 4, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 14, 4, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 15, 5, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 16, 6, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 17, 7, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 18, 8, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 19, 8, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 20, 8, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 21, 8, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 22, 6, 6);
