DECLARE @Layout VARCHAR(50) = '12 Jogadores, 4 Perguntas mesmo Tema';
DECLARE @IdLayout int;
DECLARE @IdTrilha INT;

SET @IdLayout = (SELECT L.Id FROM LayoutTabuleiro L WHERE L.Descricao = @Layout);
PRINT @IdLayout;

SET @IdTrilha = 10;
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 01, 7, 0);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 02, 7, 1);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 03, 7, 2);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 04, 7, 3);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 05, 7, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 06, 6, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 07, 5, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 08, 4, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 09, 4, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 10, 4, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 11, 4, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 12, 4, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 13, 5, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 14, 6, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 15, 7, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 16, 8, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 17, 8, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 18, 8, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 19, 8, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 20, 8, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 21, 7, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 22, 6, 6);

SET @IdTrilha = 11;
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 01, 6, 0);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 02, 6, 1);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 03, 6, 2);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 04, 6, 3);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 05, 6, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 06, 5, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 07, 4, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 08, 4, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 09, 4, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 10, 4, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 11, 4, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 12, 5, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 13, 6, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 14, 7, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 15, 8, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 16, 8, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 17, 8, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 18, 8, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 19, 8, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 20, 7, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 21, 6, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 22, 6, 6);

SET @IdTrilha = 12;
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 01, 5, 0);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 02, 5, 1);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 03, 5, 2);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 04, 5, 3);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 05, 5, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 06, 4, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 07, 4, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 08, 4, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 09, 4, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 10, 4, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 11, 5, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 12, 6, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 13, 7, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 14, 8, 8);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 15, 8, 7);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 16, 8, 6);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 17, 8, 5);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 18, 8, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 19, 7, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 20, 6, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 21, 5, 4);
INSERT INTO TrilhasTabuleiro (IdLayout, IdTrilha, IdSequencia, Linha, Coluna) VALUES (@IdLayout, @IdTrilha, 22, 6, 6);
